dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache/

php:
  - 7.1

services:
  - mysql
  - redis-server

env:
  - SYMFONY_VERSION="3.2.*"
  - SYMFONY_VERSION="3.3.*"
  - SYMFONY_VERSION="3.4.*"

matrix:
  include:
    - php: 7.0
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.2
      env: SYMFONY_VERSION="3.4.*"
  fast_finish: true

addons:
  firefox: "latest-esr"
  hosts:
    - fr.victoire.io
    - en.victoire.io

# Use public URLs for git submodule in order to avoid API rate limit
# Source: https://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci/24600210#24600210
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

before_script:
  - phpenv config-add travis.php.ini
  - npm install less
  - mkdir fails
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --no-interaction -vv --profile --no-progress
  - cp -v Tests/App/app/config/parameters.yml.dist Tests/App/app/config/parameters.yml
  # Update MySQL database user
  - "sed -i 's#dbuser: \"ubuntu\"#dbuser: \"root\"#' Tests/App/app/config/parameters.yml"
  # Disable code coverage for Behat
  - "sed -i '/CoverageContext/d' behat.yml* && echo \"CoverageContext disabled\""
  # Prepare database
  - php Tests/App/bin/console --env=ci doctrine:database:create
  - php Tests/App/bin/console --env=ci doctrine:schema:create
  - php Tests/App/bin/console --env=ci cache:warmup
  - php Tests/App/bin/console --env=ci victoire:generate:view
  - php Tests/App/bin/console --env=ci assets:install Tests/App/web
  - php Tests/App/bin/console --env=ci bazinga:js-translation:dump
  - php Tests/App/bin/console --env=ci fos:js:dump --target="Tests/App/web/js/fos_js_routes_test.js"
#  - php Tests/App/bin/console --env=domain fos:js:dump --target="Tests/App/web/js/fos_js_routes_domain.js"
  - php Tests/App/bin/console --env=ci assetic:dump
  - nohup php Tests/App/bin/console --env=ci server:run -r Tests/App/app/config/router_ci.php &
  # Run selenium server
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.1.jar"
  - "nohup java -jar selenium-server-standalone-3.8.1.jar > /dev/null &"
  - sleep 5

script:
  - './vendor/bin/behat Tests/Features/Navigation/authentication.feature'
  - './vendor/bin/behat Tests/Features/Widget/delete.feature'
