sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
#  - 5.6
  - 7.0
#  - hhvm

services:
  - mysql
  - redis-server

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.2.*"

addons:
  hosts:
    - fr.victoire.io
    - en.victoire.io

before_script:
  - phpenv config-add travis.php.ini
  - npm install less
  - mkdir fails
  - composer self-update
  - COMPOSER_ROOT_VERSION=2.2 composer require symfony/symfony:${SYMFONY_VERSION} $DEPENDENCY --no-update
  - composer install --no-interaction -vv --profile --no-progress
  # Prepare database
  - php Tests/Functionnal/bin/console --env=test doctrine:database:create
  - php Tests/Functionnal/bin/console --env=test doctrine:schema:create
  - php Tests/Functionnal/bin/console --env=test cache:warmup
  - php Tests/Functionnal/bin/console --env=test victoire:generate:view
  - php Tests/Functionnal/bin/console --env=test assets:install Tests/Functionnal/web
  - php Tests/Functionnal/bin/console --env=test bazinga:js-translation:dump
  - php Tests/Functionnal/bin/console --env=test fos:js:dump --target="Tests/Functionnal/web/js/fos_js_routes_test.js"
  - php Tests/Functionnal/bin/console --env=domain fos:js:dump --target="Tests/Functionnal/web/js/fos_js_routes_domain.js"
  - php Tests/Functionnal/bin/console --env=test assetic:dump
  - nohup php Tests/Functionnal/bin/console --env=test server:run -r vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_prod.php &
  # Run selenium server
#  - "sh -e /etc/init.d/xvfb start"
#  - "export DISPLAY=:99.0"
#  - "wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar"
#  - "nohup java -jar selenium-server-standalone-2.53.1.jar > /dev/null &"
  - sleep 5

script:
#  - './vendor/bin/behat'
  - 'phpunit --coverage-text'

after_script:
  - php Tests/Functionnal/bin/console --env=test doctrine:database:drop --force

after_failure:
  - vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "fails/*.log"
  - vendor/lakion/mink-debug-extension/travis/tools/upload-screenshots "fails/*.png"

cache:
  directories:
    - $HOME/.composer/cache

notifications:
    slack: appventus:Xy4yq4kXpBK9XHgfz8t9VBPl
